languageCode = 'en-us'
baseURL = "https://example.org.com"
title = "Muhammad Abyaz | Engineering Student"

ignoreErrors = ["error-remote-getjson"]

[Params]
description = "As a passionate developer, I aspire to evolve into a backend engineer. Explore my portfolio to witness the intersection of creativity and technical prowess in crafting robust backend solutions."

[Params.Terminal]
scheme = "monokai"

userName = "abyaz"
pcName = "workstation"
workDir = "about"
profile = "profile.txt"

ps1Delay = 0      # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
stdoutDelay = 0   # stdout speed : [description] , files in Params.Tree
commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/

titleDelay = 0   # title speed : "title" in front matter
contentDelay = 0 # content speed : content in .md file

# activityDelay = 5 : deprecated

description = """
  Hi I am Muhammad Abyaz!
  Nice to meet you! 👋
  I am a 1st year Engineering student 😊
  """

# Note: If you want to use a Markdown file, you can use the following
# description = "/description.md"
# Note: and put the description.md in /content/description.md

[Params.Tree]
use = true
folderName = "skills"
# Note: ["ACTIVITY", "URL or PATH TO YOUR MARKDOWN FILE"]
files = [["Java", "#"], ["Python", "#"]]

[module]
[[module.imports]]
path = 'github.com/yukuro/hugo-theme-shell'

[module.hugoVersion]
extended = true
min = "0.85.0"
